name: WakaTime Readme

on:
  schedule:
    # ë§¤ì¼ ë°¤ 12ì‹œ(UTC) ì‹¤í–‰
    - cron: '0 0 * * *'
  workflow_dispatch: # ìˆ˜ë™ ì‹¤í–‰ ê°€ëŠ¥

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }} 
          # ðŸ‘† ìœ„ ë¶€ë¶„ì´ ë°”ë€Œì—ˆìŠµë‹ˆë‹¤. (GITHUB_TOKEN -> GH_TOKEN)
          
          # ì„¤ì • ì˜µì…˜
          SHOW_OS: "False"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_COMMIT: "False"
          SHOW_LANGUAGE: "True"
          SHOW_LINES_OF_CODE: "True"
