name: WakaTime Readme

on:
  schedule:
    # 매일 밤 12시(UTC) 실행
    - cron: '0 0 * * *'
  workflow_dispatch: # 수동 실행 가능

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write # 403 권한 에러 방지
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          # 아래 설정들만 남기고 나머지는 다 지웠습니다.
          SHOW_OS: "False"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_COMMIT: "False"
          SHOW_LANGUAGE: "True"
          SHOW_LINES_OF_CODE: "True"
